# Generated by Django 4.1 on 2023-03-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofcrime', models.CharField(max_length=100)),
                ('crimelocation', models.CharField(max_length=20)),
                ('timehappened', models.CharField(max_length=10)),
                ('datehappened', models.CharField(max_length=50, unique=True)),
                ('victim', models.CharField(max_length=200)),
                ('suspect', models.CharField(max_length=20)),
                ('crimestory', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
