# Generated by Django 4.1 on 2023-04-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_createpost_filecase_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecase',
            name='accuser',
        ),
    ]
