# Generated by Django 4.1 on 2023-03-23 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_filecase_delete_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecase',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='filecase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
