# Generated by Django 4.1 on 2023-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_filecase_options_filecase_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecase',
            name='datehappened',
            field=models.CharField(max_length=50),
        ),
    ]
