# Generated by Django 4.1 on 2023-04-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_filecase_accuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecase',
            name='accuser',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filecase',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
