# Generated by Django 4.1 on 2023-04-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_filecase_accuser_alter_filecase_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecase',
            name='accuser',
        ),
        migrations.RemoveField(
            model_name='filecase',
            name='email',
        ),
    ]
