# Generated by Django 4.1 on 2023-04-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_filecase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecase',
            name='user',
        ),
        migrations.AddField(
            model_name='filecase',
            name='email',
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
