# Generated by Django 4.1 on 2023-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_filecase_accuser_remove_filecase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecase',
            name='accuser',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='filecase',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
