# Generated by Django 4.1 on 2023-04-12 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_createpost_alter_filecase_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='createpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
