# Generated by Django 4.1 on 2023-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecase',
            name='accuser',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
