# Generated by Django 4.1 on 2023-05-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_filecase_accuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecase',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
