# Generated by Django 4.1 on 2023-04-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_filecase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecase',
            name='email',
        ),
    ]
