# Generated by Django 4.1 on 2023-04-26 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleuser',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='peopleuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='peopleuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='peopleuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='peopleuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='peopleuser',
            name='password',
        ),
        migrations.AddField(
            model_name='peopleuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
